id: P000285
initial_creation_type: ocr
created_at: 21/02/2020
last_modified_at: 2021-12-16 15:32:01.549542
source_metadata:
  id: bdr:W7732
  title: སུམ་པ་ཡེ་ཤེས་དཔལ་འབྱོར་གྱི་རང་རྣམ
  author: ''
  volumes:
    5abbdc42d25c474f8924d3445c5d817d:
      image_group_id: I1GS140299
      title: Volume 1 of ye shes dpal 'byor gyi rnam thar
      volume_number: 1
      total_pages: 109
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
